backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "src/_assets/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/img" # The src attribute for uploaded media will begin with /images/uploads

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "files"
    label: "Root files"
    folder: "_pages"
    create: true
    slug: "{{path}}"
    fields:
      - { label: "Template", name: "template", widget: "string" }
      - { label: "Body of the post", name: "body", widget: "markdown" }
