backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to main)

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "src/_assets/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/img" # The src attribute for uploaded media will begin with /images/uploads

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "files" # Used in routes, e.g., /admin/collections/blog
    label: "Root files" # Used in the UI
    folder: "_pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{template}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Template", name: "template", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - label: "Head"
        name: "head"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
  - name: "it-laitteet"
    label: "It-laitteet"
    folder: "_pages/it-laitteet"
    identifier_field: path
    create: true
    slug: "{{path}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Path", name: "path", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - label: "Head"
        name: "head"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Keywords", name: "keywords", widget: "string" }
      - label: "Contact Form"
        name: "contactForm"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Id", name: "id", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
  - name: "it-palvelut"
    label: "It-palvelut"
    folder: "_pages/it-palvelut"
    create: true
    identifier_field: path
    slug: "{{path}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Path", name: "path", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - label: "Head"
        name: "head"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Keywords", name: "keywords", widget: "string" }
      - label: "Contact Form"
        name: "contactForm"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Id", name: "id", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
  - name: "uusi-yrittaja"
    label: "uusi-yrittaja"
    folder: "_pages/uusi-yrittaja"
    create: true
    identifier_field: path
    slug: "{{path}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Path", name: "path", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - label: "Head"
        name: "head"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Keywords", name: "keywords", widget: "string" }
      - label: "Contact Form"
        name: "contactForm"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Id", name: "id", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
  - name: "yritys"
    label: "yritys"
    folder: "_pages/yritys"
    create: true
    identifier_field: path
    slug: "{{path}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Path", name: "path", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - label: "Head"
        name: "head"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Keywords", name: "keywords", widget: "string" }
      - label: "Contact Form"
        name: "contactForm"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Id", name: "id", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
